# Generated by Django 4.0.3 on 2022-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='task_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='task_name',
            new_name='product_name',
        ),
    ]
