# Generated by Django 4.0.3 on 2022-10-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ManyToManyField(to='crud.category'),
        ),
    ]
