# Generated by Django 4.0.3 on 2022-10-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_remove_product_category_name_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crud.category'),
        ),
    ]
